insert into Roles (role_ID, role_Name, is_project_admin) VALUES (1, 'admin', 1)
insert into Users (user_ID, fullname, email, [password], role_id) VALUES (1, 'Thang', 'doanvanthang4271@gmail.com', 'abc', 1)
insert into Milestones (milestone_ID, milestone_Name, due_on, [project_id], [status]) VALUES (1, 'Test milestone', getDate(), 1, 0)
insert into TestRun (run_ID, run_Name, created_on, milestone_id, user_id, project_id, is_completed, include_all, failed_count, passed_count, retest_count, untested_count) values (1, 'test run', getdate(), 1, 1, 1, 1, 1, 3, 4, 6, 3)
insert into TestPlan (plan_ID, plan_Name, project_id, milestone_id) VALUES (1, 'plan name', 1, 1)
insert into Sections (section_ID, section_Name, project_id, plan_id) VALUES (1, 'section name', 1, 1)
insert into Priorities(priorities_id, priority_name, priority_count, short_name, is_default, is_delete)
values(1,'priority name', 2, 'short name', 1, 1)
insert into [Status] (status_ID, status_Name, is_active, is_untested, is_final)
values (1, 'PASSED', 1, 1, 1)
insert into testcase (case_ID, case_Name, estimate, section_id, priority_id, user_id, status_id, is_deleted, created_on, updated_on, updated_by, [status])
VALUES (1, 'test case', 2, 1, 1, 1, 1, 1, GETDATE(), GETDATE(), 1, 1)
select * from TestCase
